//ChatGPT made a bunch of these up

const chessOpenings = {
    "King's Pawn Opening": "https://www.chess.com/openings/Kings-Pawn-Opening",
    "Queen's Pawn Opening": "https://www.chess.com/openings/Queens-Pawn-Opening",
    "Italian Game": "https://www.chess.com/openings/Italian-Game",
    "French Defense": "https://www.chess.com/openings/French-Defense",
    "Caro-Kann Defense": "https://www.chess.com/openings/Caro-Kann-Defense",
    "Ruy Lopez": "https://www.chess.com/openings/Ruy-Lopez-Opening",
    "Sicilian Defense": "https://www.chess.com/openings/Sicilian-Defense",
    "Queen's Gambit": "https://www.chess.com/openings/Queens-Gambit-Declined",
    "King's Indian Defense": "https://www.chess.com/openings/Kings-Indian-Defense",
    "Nimzo-Indian Defense": "https://www.chess.com/openings/Nimzo-Indian-Defense",
    "Gruenfeld Defense": "https://www.chess.com/openings/Gruenfeld-Defense",
    "Modern Defense": "https://www.chess.com/openings/Modern-Defense",
    "English Opening": "https://www.chess.com/openings/English-Opening",
    "Alekhine's Defense": "https://www.chess.com/openings/Alekhines-Defense",
    "Scandinavian Defense": "https://www.chess.com/openings/Scandinavian-Defense",
    "Dutch Defense": "https://www.chess.com/openings/Dutch-Defense",
    "Pirc Defense": "https://www.chess.com/openings/Pirc-Defense",
    "Benoni Defense": "https://www.chess.com/openings/Benoni-Defense",
    "King's Indian Attack": "https://www.chess.com/openings/Kings-Indian-Attack",
    "Grünfeld Defense": "https://www.chess.com/openings/Gruenfeld-Defense",
    "Catalan Opening": "https://www.chess.com/openings/Catalan-Opening",
    "Slav Defense": "https://www.chess.com/openings/Slav-Defense",
    "Queen's Indian Defense": "https://www.chess.com/openings/Queens-Indian-Defense",
    "King's Indian Defense": "https://www.chess.com/openings/Kings-Indian-Defense",
    "Nimzowitsch Defense": "https://www.chess.com/openings/Nimzowitsch-Defense",
    "Scotch Game": "https://www.chess.com/openings/Scotch-Game",
    "Vienna Game": "https://www.chess.com/openings/Vienna-Game",
    "Four Knights Game": "https://www.chess.com/openings/Four-Knights-Game",
    "Scotch Gambit": "https://www.chess.com/openings/Scotch-Gambit",
    "King's Gambit": "https://www.chess.com/openings/Kings-Gambit",
    "Falkbeer Counter-Gambit": "https://www.chess.com/openings/Falkbeer-Counter-Gambit",
    "Danish Gambit": "https://www.chess.com/openings/Danish-Gambit",
    "Göring Gambit": "https://www.chess.com/openings/Goring-Gambit",
    "Evans Gambit": "https://www.chess.com/openings/Evans-Gambit",
    "Blackmar-Diemer Gambit": "https://www.chess.com/openings/Blackmar-Diemer-Gambit",
    "Albin Counter-Gambit": "https://www.chess.com/openings/Albin-Counter-Gambit",
    "Benko Gambit": "https://www.chess.com/openings/Benko-Gambit",
    "Budapest Gambit": "https://www.chess.com/openings/Budapest-Gambit",
    "Blumenfeld Gambit": "https://www.chess.com/openings/Blumenfeld-Gambit",
    "Bogo-Indian Defense": "https://www.chess.com/openings/Bogo-Indian-Defense",
    "Old Indian Defense": "https://www.chess.com/openings/Old-Indian-Defense",
    "Grob's Attack": "https://www.chess.com/openings/Grobs-Attack",
    "Bird Opening": "https://www.chess.com/openings/Bird-Opening",
    "Ware Opening": "https://www.chess.com/openings/Ware-Opening",
    "Saragossa Opening": "https://www.chess.com/openings/Saragossa-Opening",
    "Hungarian Opening": "https://www.chess.com/openings/Hungarian-Opening",
    "Nimzowitsch-Larsen Attack": "https://www.chess.com/openings/Nimzowitsch-Larsen-Attack",
    "Van't Kruijs Opening": "https://www.chess.com/openings/Vant-Kruijs-Opening",
    // Additional Openings
    "Colle System": "https://www.chess.com/openings/Colle-System",
    "London System": "https://www.chess.com/openings/London-System",
    "Trompowsky Attack": "https://www.chess.com/openings/Trompowsky-Attack",
    "King's Indian Attack": "https://www.chess.com/openings/Kings-Indian-Attack",
    "Barcza System": "https://www.chess.com/openings/Barcza-System",
    "Réti Opening": "https://www.chess.com/openings/Reti-Opening",
    "Zukertort Opening": "https://www.chess.com/openings/Zukertort-Opening",
    "Torre Attack": "https://www.chess.com/openings/Torre-Attack",
    "London System": "https://www.chess.com/openings/London-System",
    "Colle-Zukertort System": "https://www.chess.com/openings/Colle-Zukertort-System",
    "Stonewall Attack": "https://www.chess.com/openings/Stonewall-Attack",
    "Veresov Opening": "https://www.chess.com/openings/Veresov-Opening",
    "Jobava London System": "https://www.chess.com/openings/Jobava-London-System",
    "Blackmar-Diemer Gambit Declined": "https://www.chess.com/openings/Blackmar-Diemer-Gambit-Declined",
    "Wade Defense": "https://www.chess.com/openings/Wade-Defense",
    "Englund Gambit": "https://www.chess.com/openings/Englund-Gambit",
    "Chigorin Defense": "https://www.chess.com/openings/Chigorin-Defense",
    "Tarrasch Defense": "https://www.chess.com/openings/Tarrasch-Defense",
    "Semi-Slav Defense": "https://www.chess.com/openings/Semi-Slav-Defense",
    "QGD Exchange Variation": "https://www.chess.com/openings/QGD-Exchange-Variation",
    "Bogo-Indian Defense": "https://www.chess.com/openings/Bogo-Indian-Defense",
    "Queen's Fianchetto Defense": "https://www.chess.com/openings/Queens-Fianchetto-Defense",
    "Hedgehog Defense": "https://www.chess.com/openings/Hedgehog-Defense",
    "Bird's Opening": "https://www.chess.com/openings/Birds-Opening",
    "King's English Variation": "https://www.chess.com/openings/Kings-English-Variation",
    "Reti Gambit": "https://www.chess.com/openings/Reti-Gambit",
    "Tarrasch Variation": "https://www.chess.com/openings/Tarrasch-Variation",
    "Chigorin Variation": "https://www.chess.com/openings/Chigorin-Variation",
    "Slav Gambit": "https://www.chess.com/openings/Slav-Gambit",
    "Symmetrical Defense": "https://www.chess.com/openings/Symmetrical-Defense",
    "Philidor Defense": "https://www.chess.com/openings/Philidor-Defense",
    "Pterodactyl Defense": "https://www.chess.com/openings/Pterodactyl-Defense",
    "Modern Benoni": "https://www.chess.com/openings/Modern-Benoni",
    "Semi-Benoni": "https://www.chess.com/openings/Semi-Benoni",
    "Benoni Accelerated Fianchetto": "https://www.chess.com/openings/Benoni-Accelerated-Fianchetto",
    "Benko Gambit Accepted": "https://www.chess.com/openings/Benko-Gambit-Accepted",
    "Benko Gambit Declined": "https://www.chess.com/openings/Benko-Gambit-Declined",
    "Old Benoni Defense": "https://www.chess.com/openings/Old-Benoni-Defense",
    "Snake Benoni": "https://www.chess.com/openings/Snake-Benoni",
    "Volga Gambit": "https://www.chess.com/openings/Volga-Gambit",
    "Grivas Sicilian": "https://www.chess.com/openings/Grivas-Sicilian",
    "Closed Sicilian": "https://www.chess.com/openings/Closed-Sicilian",
    "Sicilian Accelerated Dragon": "https://www.chess.com/openings/Sicilian-Accelerated-Dragon",
    "Sicilian Alapin": "https://www.chess.com/openings/Sicilian-Alapin",
    "Sicilian Dragon": "https://www.chess.com/openings/Sicilian-Dragon",
    "Sicilian Grand Prix Attack": "https://www.chess.com/openings/Sicilian-Grand-Prix-Attack",
    "Sicilian Najdorf": "https://www.chess.com/openings/Sicilian-Najdorf",
    "Sicilian Scheveningen": "https://www.chess.com/openings/Sicilian-Scheveningen",
    "Sicilian Sveshnikov": "https://www.chess.com/openings/Sicilian-Sveshnikov",
  };
  
  // Example usage:
  console.log(chessOpenings["Colle System"]); // Output: https://www.chess.com/openings/Colle-System
  